num_epochs: 200
learning_rate: 0.0001
momentum: 0.5
weight_decay: 0.01
dampening: 0.1
optimizer: "SGD"
lr_scheduler: ""
sampler: ""
loss_function: "cross_entropy"
batch_size: 3
train_split_percentage: 0.9
classes: [1, 3]
max_images_per_class: 5000
max_frame_size: 29
width_crop_size: 0
height_crop_size: 0
split_type: "balanced"

#station_info:
#  DSPECT:
#    - RST._U_TF_SD._SA
#    - RST._S_TF_SD._SA
#    - STR._U_TF_SD._SA
#    - STR._S_TF_SD._SA

station_info:
  BrightView:
    - SAX-STR
    - SAX-RST
  PHLPSSCT001AG00:
    - SAX-AST-AC-STR
    - SAX-AST-AC-RST
  P3000XP328:
    - SAX-STR
    - SAX-RST

